config/routes.rb
Rails.application.routes.draw do
  resources :chats
  # namespace :api do 
  # 	namespace :v1 do
  		get  'virus/index' 
  # 	end
  # end
  root 'chats#index'
	require 'sidekiq/web'
	mount Sidekiq::Web => '/sidekiq'


	scope '/contributors' do
		post :donate, to: 'contributors#donate', as: 'contributor_donate'
		get :success, to: 'contributors#success', as: 'contributor_success'
		get :cancel, to: 'contributors#cancel', as: 'contributor_cancel'
	end
	
	#root to: "contributors#index"
	devise_for :contributors
	
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  has_many :credit_cards, dependent: :destroy

  after_commit :assign_customer_id, on: :create

  def assign_customer_id
  	customer = Stripe::Customer.create(email: email)
  	self.customer_id = customer.id
  end

  def price_cents
  	(price * 100).to_i
  end
  
end

app/controllers/api/v1/virus_controller.rb
class VirusController < ApplicationController
	def index
		# conn = Faraday.new
		# response = conn.get do |req|
		# 	req.url("https://api.covid19api.com/all")
		# end
		# data = JSON.parse(response.body)
		# # binding.pry
		 render :index
	end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  # GET /chats.json
  def index
    
@chats =Chat.all 
    @chat = Chat.new 
  end

  # GET /chats/1
  # GET /chats/1.json
  def show
  end

  # GET /chats/new
  def new
    @chats =Chat.all 
    @chat = Chat.new
  end

  # GET /chats/1/edit
  def edit
  end

  # POST /chats
  # POST /chats.json
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        ActionCable.server.broadcast 'room_channel', content: @chat 
        format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        format.json { render :show, status: :created, location: @chat }
        format.js
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/1
  # PATCH/PUT /chats/1.json
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/1
  # DELETE /chats/1.json
  def destroy
    @chat.destroy
     ActionCable.server.broadcast 'remove_channel', content: @chat 
    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:message)
    end
end

app/controllers/contributors_controller.rb
class ContributorsController < ApplicationController

  def index
		@con =Contributor.all
	end
		
  def add_bio
  	@con =Contributor.find_by(params[:id])
  end
  
  def update
  	@con =Contributor.find_by(params[:id])
  	if @con.update_attributes(contributor_params)
  		flash[:notice] = 'successfully added'
  		redirect_to contributors_path
  	else
  		flash[:notice] = 'un-successfully added'

  	end
  end

  def donate
    con =Contributor.find(params[:id])
    	if con.nil?
    		redirect_to root_path
    		return
    	end
      Stripe.api_key = 'sk_test_aYaoJEgGoHQ7zg3BqwHytxhF008qpb5fTN'
   	@session = Stripe::Checkout::Session.create(
   		payment_method_types: ['card'],
   		line_items: [{
   		name: con.email,
      description: 'User',
   		amount: con.price_cents,
   		currency: 'INR',
   		quantity: 1
   		}],
   		success_url: contributor_success_url,
		  cancel_url: contributor_cancel_url
	  )
 	
    respond_to do |format|
   		format.js
   	end
  end

  def success
    
  end

  private
    def contributor_params
   	  params.require(:contributor).permit(:bio,:price)
    end

end

app/controllers/virus_controller.rb
class VirusController < ApplicationController
	def index
		# conn = Faraday.new
		# response = conn.get do |req|
		# 	req.url("https://api.covid19api.com/all")
		# end
		# data = JSON.parse(response.body)
		# # binding.pry
		 render :index
	end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/virus_helper.rb
module VirusHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: @chat) do |f| %>
  <%= f.label :message %>
  <%= f.text_field :message %>


  <%= f.submit %>
<% end %>

app/views/chats/edit.html.erb
<h1>Editing Chat</h1>

<%= render 'form', chat: @chat %>

<%= link_to 'Show', @chat %> |
<%= link_to 'Back', chats_path %>

app/views/chats/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chats</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.message %></td>
        <td><%= link_to 'Show', chat %></td>
        <td><%= link_to 'Edit', edit_chat_path(chat) %></td>
        <td><%= link_to 'Destroy', chat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chat', new_chat_path %>

app/views/chats/new.html.erb
<h1>New Chat</h1>
<% @chats.each do |chat| %>
<p id="<%=chat.id%>"><%= chat.message %></p>
<% end %>
<div id="new_message"></div>
<%= render 'form', chat: @chat %>

<%= link_to 'Back', chats_path %>

app/views/chats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @chat.message %>
</p>

<%= link_to 'Edit', edit_chat_path(@chat) %> |
<%= link_to 'Back', chats_path %>

app/views/contributors/donate.js.erb
const stripe = Stripe('<%=Rails.configuration.stripe[:publishable_key]%>');
stripe.redirectToCheckout({
	sessionId: '<%=@session.id%>'
}).then(function (result) {
	console.log(result.error.message);
})

app/views/contributors/index.html.erb
<tr class="active">
    email</tr>

<div class="container">
<% if contributor_signed_in? %>
<fieldset>
<%=link_to "Add Bio", add_bio_contributor_path(current_contributor.id) %>
</fieldset>
<%else%>
<h1>All Contributors</h1>

<table class="table">
<tbody>
<tr class="success">
    <th>email</th>
    <th>Bio</th>
    <th>Price</th>
  </tr>
   
  <%@con.each do |c|%>
  <td><%=c.email%></td><td><%=c.bio%><td><%=c.price%></td></td><td><%=button_to "Donate", contributor_donate_path, method: :post, params: {id: c.id}, remote: true %></td>
  </tr>
  <%end%>
</tbody>
</table>
<%end%>
</div>

app/views/contributors/success.html.erb
<h1>Payment successfull <h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donations</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
 <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
     -->

  <!-- <meta name="stripe-key" content="<%#= ENV['PUBLISHABLE_KEY'] %>" /> -->
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<!-- <script src="https://js.stripe.com/v3/"></script>
<p class="navbar-text float-right">
  <% if contributor_signed_in? %>
  Logged in as <strong><%= current_contributor.email %></strong>.
  <%= link_to 'Edit profile', edit_contributor_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_contributor_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
  <%= link_to "Sign up", new_contributor_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_contributor_session_path, :class => 'navbar-link'  %>
  <% end %>
</p>
<body> -->
  <%= yield %>
</body>
</html>

app/views/virus/index.html.erb
 
 <%= react_component 'Main' %>
 <%#= react_component("HelloReact", { greeting: "Hello from react-rails." }) %>
<%#= javascript_pack_tag 'hello_react' %>